services:
  rocky9php81:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL9
  rocky9php81reloc:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL9

volumes:
  rpm9rocky:
    name: rpm9rocky
