version: "3"
services:
  stream8php81:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
  stream8php81rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8

volumes:
  rpm8stream:
    name: rpm8stream
