version: "3.5"
services:
  centos7php81dev:
    build:
      context: dev
      args:
        centos: $OS7
    image: aursu/php81build:${OS7TAG}-dev
  centos8php81dev:
    build:
      context: dev
      args:
        centos: $OS8
    image: aursu/php81build:${OS8TAG}-dev
  centos7php81dev2:
    build:
      context: dev
      args:
        centos: $OS7
        image: dev2base
    image: aursu/php81build:${OS7TAG}-dev2
  centos8php81dev2:
    build:
      context: dev
      args:
        centos: $OS8
        image: dev2base
    image: aursu/php81build:${OS8TAG}-dev2