version: "3"
services:
  centos7php81run:
    build:
      context: .
      args:
        centos: $OS7
    image: aursu/php81build:${OS7TAG}-runtime
  centos7php81devbase:
    build:
      context: .
      args:
        centos: $OS7
        image: node16dev
    image: aursu/php81build:${OS7TAG}-devbase