services:
  rocky9php81dev:
    build:
      context: dev
      args:
        os: $RL9
    image: "aursu/php81build:${RL9TAG}-dev"
  rocky9php81dev2:
    build:
      context: dev
      args:
        os: $RL9
        image: dev2base
    image: "aursu/php81build:${RL9TAG}-dev2"